import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
// Basic Authentication
const Home: NextPage = () => {
  const [email, setEmail] = React.useState('');
  const [password, setPassword] = React.useState(''); //React.useReducer(initialState,reducer)

  const onSubmitHandler = () => {
    fetch('/api/login', {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Basic ${Buffer.from(`${email}:${password}`).toString(
          'base64'
        )}`,
      },
    }).then((res) => res.json().then((data) => {}));
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='flex flex-col gap-2 p-2'>
          <h1>Login User</h1>
          <input
            type='email'
            className='border border-gray-400 p-2 w-1/2'
            placeholder='Input your Email Address'
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
          <input
            type='password'
            className='border border-gray-400 p-2 w-1/2'
            placeholder='Input your Password'
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
          <button
            className='bg-blue-600 w-1/2 p-2 rounded-sm text-white cursor-pointer'
            onClick={onSubmitHandler}>
            Login
          </button>
        </div>
      </main>
    </div>
  );
};

export default Home;
