import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
// Basic Authentication
/*
    Basic Auth -> JWT it has expiry
*/
const Home: NextPage = () => {
  const [email, setEmail] = React.useState('');
  const [password, setPassword] = React.useState(''); //React.useReducer(initialState,reducer)
  const [sensetiveData, setSensetiveData] = React.useState('');

  const onSubmitHandler = () => {
    fetch('/api/login', {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Basic ${Buffer.from(`${email}:${password}`).toString(
          'base64'
        )}`,
      },
    })
      .then((res) =>
        res.json().then((data) => {
          console.log('Stored ', data.token);
          localStorage.setItem('idToken', data.token);
        })
      )
      .catch((error) => {
        console.log('Error = ', error.message);
        setSensetiveData('');
      });
  };

  const onGetDataHandler = () => {
    fetch('/api/protected/user-details', {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${localStorage.getItem('idToken')}`,
      },
    }).then((res) =>
      res.json().then((data) => {
        if (data.loggedIn) setSensetiveData(data.data ?? '');
        else console.log('Error = ', data);
      })
    );
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <div className='flex flex-col gap-2 p-2'>
          <h1>Login User</h1>
          <input
            type='email'
            className='w-1/2 p-2 border border-gray-400'
            placeholder='Input your Email Address'
            value={email}
            onChange={(e) => setEmail(e.target.value)}
          />
          <input
            type='password'
            className='w-1/2 p-2 border border-gray-400'
            placeholder='Input your Password'
            value={password}
            onChange={(e) => setPassword(e.target.value)}
          />
          <button
            className='w-1/2 p-2 text-white bg-blue-600 rounded-sm cursor-pointer'
            onClick={onSubmitHandler}>
            Login
          </button>
          <button
            className='w-1/2 p-2 text-white bg-blue-600 rounded-sm cursor-pointer'
            onClick={onGetDataHandler}>
            Get Protected Data
          </button>
          {sensetiveData !== '' && <p>Sensetive Data: {sensetiveData}</p>}
        </div>
      </main>
    </div>
  );
};

export default Home;
